baseurl = "https://heinhtetkyaw.me"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Diary"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
enableEmoji = true
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
disqusShortname = "heinhtetkyaw"
googleAnalytics = "UA-118963687-2"
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
post = "/:title/"

[Params]
# homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Author from Golden Land Myanmar"
  logo = "img/avatar-logo.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "Jan 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  gcse = "003623834011720940587:b1tdlq4ypqy" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Kiddo"
  since = "2012"
  website = "https://heinhtetkyaw.me"
  email = "me@heinhtetkyaw.me"
  facebook = "h2kyaw"
  googleplus = "+HeinHtetKyaw" # or xxxxxxxxxxxxxxxxxxxxx
  github = "h2kyaw"
  twitter = "HeinHtetKyaw_"
  instagram = "CallMePuTuTuLay"
  youtube = "Kiddo-MUA" # or channel/channelname
  telegram = "HeinHtetKyaw"

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2

[[menu.main]]
  name = "Books"
  identifier = "/books"
  url = "books"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 4